def print_help(version):
	print("\n            ,,,                         ,,,")
	print("      &@@@@@@@@@@@@@              @@@@@@@@@@@@@@")
	print("    @@@@@@@#    %@@@@@#        @@@@@@@@@@@@@@@@@@@@")
	print("  @@@@@@            #@@@     &@@@@@@@         @@@@@@")
	print(" @@@@@                @@@@  @@@@@@@             @@@@@")
	print(" @@@@                   @@@@@@@@@                @@@@@")
	print("@@@@@                    @@@@@@@                  @@@@")
	print("@@@@@                    @@@@@@                   @@@@#")
	print("@@@@@                   @@@@@@                    @@@@,")
	print("&@@@@                 &@@@@@@@@                  *@@@@")
	print(" @@@@@               @@@@@@@ @@@                 @@@@@")
	print("  @@@@@            *@@@@@@#   @@@               @@@@@")
	print("   @@@@@@#       @@@@@@@@      @@@@#          @@@@@@")
	print("    *@@@@@@@@@@@@@@@@@@          @@@@@@@@%@@@@@@@@")
	print("       #@@@@@@@@@@@@               *@@@@@@@@@@@*\n")
	print("InfiniDrive v" + version + " - An unlimited Google Drive storage solution")
	print("Based on a project by David Berdik, Steven Myrick, and Noah Greenberg\n")
	print(">> help - Displays this help command.")
	print(">> upload <file path OR http/https URL> <optional: file name> - Uploads specified file to Google Drive")
	print(">> list - Lists the names of all InfiniDrive files and their IDs")
	print(">> rename <file ID> <new file name> - Renames the file with the specified ID to the specified new name")
	print(">> download <file ID> <file path> - Downloads the contents of the specified file ID to the specified file path")
	print(">> delete <file ID> <optional flag: force-delete> - Deletes the InfiniDrive file specified by the given ID")