def print_help(version):
	print("\n            ,,,                         ,,,")
	print("      &@@@@@@@@@@@@@              @@@@@@@@@@@@@@")
	print("    @@@@@@@#    %@@@@@#        @@@@@@@@@@@@@@@@@@@@")
	print("  @@@@@@            #@@@     &@@@@@@@         @@@@@@")
	print(" @@@@@                @@@@  @@@@@@@             @@@@@")
	print(" @@@@                   @@@@@@@@@                @@@@@")
	print("@@@@@                    @@@@@@@                  @@@@")
	print("@@@@@                    @@@@@@                   @@@@#")
	print("@@@@@                   @@@@@@                    @@@@,")
	print("&@@@@                 &@@@@@@@@                  *@@@@")
	print(" @@@@@               @@@@@@@ @@@                 @@@@@")
	print("  @@@@@            *@@@@@@#   @@@               @@@@@")
	print("   @@@@@@#       @@@@@@@@      @@@@#          @@@@@@")
	print("    *@@@@@@@@@@@@@@@@@@          @@@@@@@@%@@@@@@@@")
	print("       #@@@@@@@@@@@@               *@@@@@@@@@@@*\n")
	print("InfiniDrive v" + version + " - An unlimited Google Drive storage solution")
	print("Based on a project by David Berdik, Steven Myrick, and Noah Greenberg")
	print("Developed and maintained by David Berdik and Maitree Rawat\n")
	print(">> help - Displays this help command.")
	print(">> upload <file path OR http/https URL> <optional: file name> - Uploads specified file to Google Drive")
	print(">> list - Lists the names of all InfiniDrive files")
	print(">> rename <current file name> <new file name> - Renames the file with the specified name to the specified new name")
	print(">> download <file name> <file path> - Downloads the contents of the specified file name to the specified file path")
	print(">> size <file name> - Lists the size of the specified InfiniDrive file")
	print(">> delete <file name> <optional flag: force-delete> - Deletes the specified InfiniDrive file")